os: linux
sudo: required
services: docker

language: node_js
node_js: stable

install: true

before_install:
  - docker-compose up -d

before_script:
  - docker-compose exec app npm run webdriver

script:
  - docker-compose exec app npm run prod
  - docker-compose exec app npm run lint
  - docker-compose exec app npm run test
  - docker-compose exec app npm run e2e

after_success:
  - docker-compose exec app npm run deploy -- --token ${FIREBASE_TOKEN}
