os: linux

sudo: required
services: docker

language: node_js
node_js: stable

# addons:
#   sauce_connect: true

before_install:
  - docker-compose up -d

script:
  - docker-compose exec app npm run webdriver
  - docker-compose exec app npm run prod
  - docker-compose exec app npm run lint
  - docker-compose exec app npm run test
  - docker-compose exec app npm run e2e
  - npm test

after_success:
  - docker-compose exec app npm run prod
  - docker-compose exec app npm run deploy -- --token ${FIREBASE_TOKEN}
  - npm run coveralls
