os: linux

sudo: required
services: docker

before_install:
  - docker-compose up -d

script:
  - docker-compose exec app npm test
  - docker-compose exec app npm run prod
  - docker-compose exec app npm run webdriver
  - docker-compose exec app npm run e2e

after_success:
  - docker-compose exec app npm run prod
  - docker-compose exec app firebase deploy --token ${FIREBASE_TOKEN}
