# TODO: Dockerfile
language: node_js
node_js: stable

sudo: false

cache:
  directories: node_modules

script:
  - npm test
  - npm run e2e

# Docker first
# after_success:
  # - docker-compose exec app npm run ...
  # - docker-compose exec app firebase deploy --token ${FIREBASE_TOKEN}
