os: linux
dist: trusty
sudo: required

language: node_js
node_js: stable

services: docker
install: true
# cache:
#   directories: ${HOME}/docker

# env:
#   global: DOCKER_CACHE_FILE=${HOME}/docker/cache.tar.gz

branches:
  only: master

before_install: chmod +x scripts/*.sh

before_script: scripts/build.sh
script: scripts/test.sh
after_success: scripts/deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
