matrix:
  include:
    - env: MODE=docker
      os: linux
      sudo: required
      services: docker
      language: node_js
      node_js: stable
      install: false
    - env: MODE=lint
      os: linux
      sudo: false
      language: node_js
      node_js: stable
    - env: MODE=unit
      os: linux
      sudo: false
      language: node_js
      node_js: stable
    # - env: MODE=e2e
    #   os: linux
    #   sudo: false
    #   language: node_js
    #   node_js: stable

# addons:
#   sauce_connect: true

before_install:
  - if [[ "$MODE" == "docker" ]]; then docker-compose up -d; fi

script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app npm run webdriver; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app npm run prod; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app npm run lint; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app npm run test; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app npm run e2e; fi
  - if [[ "$MODE" == "lint" ]]; then npm lint; fi
  - if [[ "$MODE" == "unit" ]]; then npm test; fi

after_success:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app npm run deploy -- --token ${FIREBASE_TOKEN}; fi
  - if [[ "$MODE" == "unit" ]]; then npm run coveralls; fi
