language: node_js

matrix:
  include:
    - env: MODE=docker
      os: linux
      sudo: required
      services: docker
      node_js: stable
      install: true
    - env: MODE=lint
      os: linux
      sudo: false
      node_js: stable
    - env: MODE=unit
      os: linux
      sudo: false
      node_js: stable
      addons:
        firefox: latest
    - env: MODE=e2e
      os: linux
      sudo: false
      node_js: stable
      addons:
        firefox: "45.0"

before_install:
  - if [[ "$MODE" == "docker" ]]; then docker-compose up -d; fi
  - if [[ "$MODE" == "unit" ]] || [[ "$MODE" == "e2e" ]]; then export DISPLAY=:99.0; fi

before_script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run webdriver; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run prod; fi
  - if [[ "$MODE" == "unit" ]] || [[ "$MODE" == "e2e" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$MODE" == "unit" ]]; then yarn add karma-firefox-launcher --dev; fi
  - if [[ "$MODE" == "e2e" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi
  - if [[ "$MODE" == "e2e" ]]; then yarn run webdriver; fi
  - if [[ "$MODE" == "e2e" ]]; then yarn run prod; fi

script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run lint; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run test; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run e2e; fi
  - if [[ "$MODE" == "lint" ]]; then yarn run lint; fi
  - if [[ "$MODE" == "unit" ]]; then yarn run test; fi
  - if [[ "$MODE" == "e2e" ]]; then yarn run e2e; fi

after_success:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run prod; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run deploy -- --token ${FIREBASE_TOKEN}; fi
