language: node_js
node_js: stable

branches:
  only: master

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - MODE=prod
    - MODE=lint
    - MODE=unit
    - MODE=e2e

os: linux
sudo: false

cache: yarn

matrix:
  include:
    - env: MODE=docker
      sudo: required
      services: docker
      install: true
      cache: docker
  exclude:
    - env: MODE=docker
      sudo: false
      cache: yarn

before_install: chmod +x scripts/*.sh
before_script: scripts/build.sh
script: scripts/test.sh
after_success: scripts/deploy.sh
