language: node_js

branches:
  only: master

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:
    - env: MODE=docker
      os: linux
      sudo: required
      services: docker
      node_js: stable
      install: true
      cache: docker
    - env: MODE=prod
      os: linux
      sudo: false
      node_js: stable
      cache: yarn
    - env: MODE=lint
      os: linux
      sudo: false
      node_js: stable
      cache: yarn
    - env: MODE=unit
      os: linux
      sudo: false
      node_js: stable
      cache: yarn
    - env: MODE=e2e
      os: linux
      sudo: false
      node_js: stable
      cache: yarn

before_install:
  - if [[ "$MODE" == "docker" ]]; then docker-compose up -d; fi

before_script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run webdriver; fi
  - if [[ "$MODE" == "unit" ]]; then yarn run lib; fi
  - if [[ "$MODE" == "e2e" ]]; then yarn run webdriver && yarn run prod; fi

script:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run prod; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run lint; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run test; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run e2e; fi
  - if [[ "$MODE" == "prod" ]]; then yarn run prod; fi
  - if [[ "$MODE" == "lint" ]]; then yarn run lint; fi
  - if [[ "$MODE" == "unit" ]]; then yarn run test; fi
  - if [[ "$MODE" == "e2e" ]]; then yarn run e2e; fi

after_success:
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run prod; fi
  - if [[ "$MODE" == "docker" ]]; then docker-compose exec app yarn run deploy -- --token ${FIREBASE_TOKEN}; fi
