version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/Frontend-Starter-Kit

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start up containers
          command: docker-compose up -d

      - run:
          name: Build the application
          command: docker-compose exec app yarn prod

      - run:
          name: Test the application
          command: |
            docker-compose exec app yarn test
            docker-compose exec app yarn codecov --token=${CODECOV_TOKEN}

      - deploy:
          name: Deploy the application
          branch: develop
          command: |
            docker-compose exec app yarn firebase use staging
            docker-compose exec app yarn deploy --token ${FIREBASE_TOKEN}

      - deploy:
          name: Deploy the application
          branch: master
          command: |
            docker-compose exec app yarn firebase use production
            docker-compose exec app yarn deploy --token ${FIREBASE_TOKEN}
